-- ============================================================================
-- Script: 01_create_schema.sql
-- Purpose: Create database schema and import cleaned CSV data
-- Database: SQLite
-- ============================================================================
