-- ============================================================================
-- Script: 02_variable_construction.sql
-- Purpose: Create derived variables and aggregate measures
-- Database: SQLite
-- ============================================================================
