-- ============================================================================
-- Script: 03_descriptive_statistics.sql
-- Purpose: Generate descriptive statistics for each sector
-- Database: SQLite
-- ============================================================================
